### ISSUE TITLE
Longer timesteps giving error in disaggregation

### ISSUE THREAD

**Issue by shahryaramd** [UW-Hydro/MetSim#110]
The timesteps larger than 360min are showing an error while running MetSim. This is the error showing up:

![image](https://user-images.githubusercontent.com/5603923/33144405-c208218a-cf71-11e7-9a8e-42e9393234ba.png)

**Comment by tbohn** [comment]
I'm not sure, but I think the timestep length should divide into 24 hours evenly.  360 min = 10 hours, not an integer divisor of 24hours.

**Comment by shahryaramd** [comment]
Actually the same error shows up for other longer timesteps of 480, 720 min also

**Comment by arbennett** [comment]
I am fairly sure this is an issue with the algorithm implemented to calculate the time of min and max daily temperatures.  If the timestep is too long it may end up being that the transition from day to night is not captured so the algorithm fails.

**Comment by jhamman** [comment]
I think we just need to raise an informative error if the disaggregation timestep is not within a reasonable bound. Maybe:

- divisible into 24 hours
- <= 6 hours

@tbohn: `360 min == 6 hours` 😉

**Comment by arbennett** [comment]
Solved in #121
