### ISSUE TITLE
MultiIndex cannot be reindexed correctly in disaggregation

### ISSUE THREAD

**Issue by StephanThober** [UW-Hydro/MetSim#111]
Using pandas (0.21.1) and xarray (0.9.1) a list of a MultiIndex is a list of tuples containing the Timestamps instead of a list of Timestamps. The following error is raised:

![screen shot 2018-01-03 at 08 03 07](https://user-images.githubusercontent.com/19333234/34511538-a431beda-f05c-11e7-83f0-a79fac60e804.png)

**Comment by jhamman** [comment]
@StephanThober - can you try updating your xarray version to 0.10 and see if that fixes your problem?

**Comment by arbennett** [comment]
As of #120 there are no longer any reindexing operations.
