### ISSUE TITLE
UTC support for new P disaggregation feature

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/MetSim#116]
The new P disaggregation feature (PR #104) has an input parameter t_pk that indicates the time of day of peak precipitation.  The values we've been supplying for this parameter have been in local time, since MetSim has been doing local time by default.

If MetSim adds functionality to handle UTC times in the output, then it might make sense to also have some way to specify the time convention (UTC or local) in the inputs.  This would only be relevant for people who use the `triangle` P disagg method, but could eventually apply to other input fields as more features are added.

@arbennett @kwhitney727 perhaps we can focus on getting PR (#104) approved/merged first, and then address the time convention in the inputs as a separate issue later?  Perhaps for now MetSim should just assume that the inputs are in the same time convention as the outputs?

**Comment by arbennett** [comment]
Solved in #154
