### ISSUE TITLE
Fix endpoints of temperature disaggregation

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#13]
Shown below are the beginning and end (respectively) of a MetSim run (black) and a MTCLIM run (red).  As can be seen, they match quite well, except for the very ends.  This is because we don't provide the right endpoints.  To calcluate them for the figures shown I was using `mean(tmin, tmax)` for the first and last days.  This is clearly incorrect, but I haven't looked into what I should be using.

## Beginning
![temp_begin](https://cloud.githubusercontent.com/assets/7518706/21669553/ac24f5da-d2c1-11e6-8696-a4cafa8d7da9.png)

## End
![temp_end](https://cloud.githubusercontent.com/assets/7518706/21669555/af9c2b2a-d2c1-11e6-8e14-ddc8b1297800.png)

**Comment by arbennett** [comment]
This is done in VIC by taking the 2nd value and 2nd to last value and repeating them.  Taking this approach in MetSim fixes the issue.

**Comment by bartnijssen** [comment]
There still seems to be a time offset though? Any idea where that originates? Same comment as for issue #14 : Please use time axis on x-axis and units on y-axis.

**Comment by arbennett** [comment]
![temp](https://cloud.githubusercontent.com/assets/7518706/21790209/7a2e4924-d68f-11e6-83be-5b566d84a2cd.png)

That was an indexing issue that came up because the first point wasn't supplied, so everything got shifted back.  Here's an updated one so you can see.

**Comment by bartnijssen** [comment]
@arbennett : If this is fixed go ahead and close the issue. It makes it easier to quickly check what is still outstanding for the first release

**Comment by arbennett** [comment]
I've left it open since it's only fixed in my fork.  When I open the pull request I'll reference all of these issues that it addresses, and when it's finally merged I'll close them all.

**Comment by bartnijssen** [comment]
I much prefer many smaller PRs that roughly correspond to individual issues rather than a single large PR at the end. They are hard to review, which means that no one actually reviews them

**Comment by arbennett** [comment]
Fixed in #17
