### ISSUE TITLE
Fix vapor pressure / humidity calculation

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#14]
The vapor pressure from mtclim (red) and metsim (black) are shown in the figure below.  At the beginning and end they match up nicely, but the middle is clearly an issue.  This section roughly corresponds to summer months.  

I am somewhat confident in the `tfmax` calculation, but unsure how.

![vp](https://cloud.githubusercontent.com/assets/7518706/21695885/7601f6a4-d340-11e6-917f-d6f85df844e9.png)

**Comment by bartnijssen** [comment]
Can you put an actual date axis on the plot and units on the y-axis. I am not sure what I am looking at, so it is hard to comment. Also, where is this location supposed to be?

**Comment by arbennett** [comment]
![vp](https://cloud.githubusercontent.com/assets/7518706/21789782/61b459f4-d68c-11e6-9b8e-35dfe99cd7b8.png)

This is taken from the Stehekin data.  The coordinates are (43.3125, -120.5625).

**Comment by arbennett** [comment]
I have found that this is an error in the calculation of the effective annual precipitation.  I seem to have a factor of 10 left off somewhere.  The code I use to calculate this is:

    parray = np.array(pd.Series(window)
                  .rolling(window=90, win_type=win_type,axis=0)
                  .mean().fillna(method='bfill'))[90:] * consts['DAYS_PER_YEAR'] 
    parray = np.maximum(parray, 8.0)

I am not sure where this factor is coming from either in my code or in the VIC 4.2 code.

**Comment by jhamman** [comment]
Is it possible this is just a units issue with the precipitation?  I'm guessing you are using VIC precipitation in mm/day whereas MTCLIM may be expecting cm/day ([ref](https://github.com/jhamman/mtclim/blob/master/mtclim43.c#L103)).

**Comment by arbennett** [comment]
That seems like the most likely issue.  I'm not sure where in VIC this conversion is happening though, since I get the same disaggregated precipitation as MTCLIM without applying any unit conversions.

**Comment by jhamman** [comment]
Right, mtclim never performed the precip disaggregation so that was handled by VIC. So, There was probably a multiply-by then divide-by thing going on within VIC.

**Comment by arbennett** [comment]
As of the current commit to my fork the discrepancy looks like this:

![vp](https://cloud.githubusercontent.com/assets/7518706/22090457/81d6e79e-dda6-11e6-99b4-a5403119508f.png)

I've narrowed the arrow down to be in the calculation of `parray` but I'm not really sure what I should be doing differently.

**Comment by bartnijssen** [comment]
How do you know it is in `parray`? If that is the case can you show plots of `parray` and its equivalent in VIC?

**Comment by arbennett** [comment]
It seems that this was mostly an issue in the calculation of `t_day` where numpy.  Here's one that's almost right on:

![vp](https://cloud.githubusercontent.com/assets/7518706/22093438/856ad898-ddba-11e6-864e-984b72408c6e.png)

**Comment by arbennett** [comment]
The issue here now appears to be just the calculation of PET:

![pet](https://cloud.githubusercontent.com/assets/7518706/22131213/768e5258-de66-11e6-89bb-24f14167a621.png)

**Comment by bartnijssen** [comment]
Progress!!

**Comment by arbennett** [comment]
Fixed in #17
