### ISSUE TITLE
revise config file order of assignments for some variables to be LHS = [user entry]

### ISSUE THREAD

**Issue by andywood** [UW-Hydro/MetSim#151]
for the following blocks, the user supplied info is on the LHS instead of RHS, which is the reverse of the rest of the config file.   it would be good to make this consistent for all vars. 

--- current --- 
[forcing_vars]
prcp = prec   # ie, [user_input_name] = [metsim_fixed_internal_varname]
tmax = t_max
tmin = t_min

[state_vars]
prcp = prec
tmax = t_max
tmin = t_min

[domain_vars]
elevation = elev
latitude = lat
longitude = lon
mask = mask

**Comment by arbennett** [comment]
Completed in #155
