### ISSUE TITLE
"triangle" option for prec_type generates biases in snow accumulation in some climates

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/MetSim#152]
- Version: `1.0.0_tri`
 - Problem:

Thorough evaluation of the `triangle` option for `prec_type` indicates that in some climates (when the diurnal temperature range passes through freezing) holding event timing fixed can lead to biases in snow accumulation.

E.g., if `t_pk` is fixed at 4 pm local time (i.e. the warm part of the day), but observed event timing exhibits a lot of scatter from one day to the next, the `triangle` method will bias the partitioning of P into rain vs snow towards rain, leading to underestimation of snow accumulation.

Under these conditions, the `uniform` method yields much more accurate snow accumulation.

In the CONUS domain, these climate conditions are almost exclusively in the western mountains (Rockies, Cascades, northern Sierra Nevada).

 - Proposed Solution:

Implement a `mix` option that uses the `uniform` approach on days for which `t_min < 0 C`, and `triangle` on all other days.

**Comment by arbennett** [comment]
@tbohn can we close this since #153 has been merged in?

**Comment by tbohn** [comment]
Yes - thanks!
