### ISSUE TITLE
add option to add a constant wind field to output when not in input

### ISSUE THREAD

**Issue by andywood** [UW-Hydro/MetSim#160]
For some applications wind is a secondary met input, and is required but can be specified as a constant, e.g., 1.5 m/s.   At present this must be tacked onto output after the fact, but can easily be generated internally and added to the output variables while MetSim is being run.  Suggest adding a constant wind option that allows user to specify a wind speed to be added to all files for all timesteps.  Alternatively the wind speed could be supplied as a domain variable, allowing for different wind speeds in different locations.

**Comment by bartnijssen** [comment]
Closed per #170
