### ISSUE TITLE
Pull out annual aggregates into the domain file

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#21]
Some aggregates such as effective annual precipitation are currently calculated within the MTCLIM implementation.  Having them be estimated using the given forcing makes these values vary from run to run, depending on the length of the input timeseries.  This can lead to inconsistencies.

For example, if 2 years of data are supposed to be disaggregated the results will be different if each year is processed separately than if they are processed together.  

For this reason we should expect that the domain file will contain these values as static numbers for each grid cell.

Do we want to require this or should we fall back on estimating the values from the given forcings, but provide a warning to the user?

**Comment by bartnijssen** [comment]
Require - this is a major problem with the current implementation of MTCLIM in VIC 4.2 and one of the reason to pull it out. It seriously messes up data assimilation and forecast projects.

**Comment by bartnijssen** [comment]
If people want to reproduce the behavior of the old VIC implementation they can do so by updating the domain file with the means over the length of the model run.

**Comment by arbennett** [comment]
Fixed in  4b8d37a 6
