### ISSUE TITLE
Add configuration validation function

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#23]
We should validate that all of the necessary parameters are set, and that they have valid values.

**Comment by arbennett** [comment]
Fixed in #37

**Comment by jhamman** [comment]
I'm going to reopen this.  I just specified a invalid option and MetSim only gave me this error message:

```Invalid configuration given.  Use `ms -h` for more information.```

running `ms-h` gives:

```$ ms -h
usage: ms [-h] [-n N_PROCESSES] config

positional arguments:
  config

optional arguments:
  -h, --help            show this help message and exit
  -n N_PROCESSES, --n-processes N_PROCESSES```

Which doesn't help me figure out which configuration option caused the error. We basically need to do a better job explaining why we exit.

**Comment by arbennett** [comment]
Could you show what your parameter set was?

**Comment by arbennett** [comment]
This was reopened with a problem that this issue wasn't trying to address. Reclosing.
