### ISSUE TITLE
distributed.protocol.core - CRITICAL - Failed to deserialize

### ISSUE THREAD

**Issue by hoseinsalehi** [UW-Hydro/MetSim#242]
Hi
I ran model with your data but it didn't work.

distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/hosein/.local/lib/python3.6/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
.
.
.
.
.
  File "/home/hosein/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
concurrent.futures._base.CancelledError: wrap_run_slice-7f60780c-edfe-4f13-b9de-4cb7ab79882b
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>
distributed.nanny - WARNING - Worker process 4528 was killed by unknown signal

How can I fix this error?

**Comment by arbennett** [comment]
Can you explain a little further how you got this error? What command did you use to run, and what data were you using?

**Comment by hoseinsalehi** [comment]
I tested 2 sample datasets.(example_ascii.conf in this repository and test.conf in MetSim-tutorial-master)
I use this command : ms ./example_ascii.conf
                                 ms ./test.conf

I check all inputs and paths are correct.


It generate a output but it's empty(I attached it).
[test_19500101-19500131.zip](https://github.com/UW-Hydro/MetSim/files/5250477/test_19500101-19500131.zip)
[error.txt](https://github.com/UW-Hydro/MetSim/files/5250481/error.txt)

**Comment by hoseinsalehi** [comment]
with updating  distributed it solved.
Thanks dear @arbennett .
