### ISSUE TITLE
unable to obtain the end state and enable simulation of subsequent time steps

### ISSUE THREAD

**Issue by kwhitney727** [UW-Hydro/MetSim#247]
In a prior MetSim version, a python script was developed "[wrap_metsim_over_time.py](https://github.com/kwhitney727/MetSim/blob/feature/time_wrap/scripts/wrap_metsim_over_time.py)" that enabled wrapping through multiple monthly forcing files over multiple years. This would initalize a parameter object "param" from a given parameter file and call metsim with "ms = MetSim(params)", then obtain and create a netcdf file with the state at the end of the simualation with "ms.state.to_netcdf(out_state)", and then feed this as the input statefile for the subsequent MetSim implementation. I am attempting to apply this wrapper script with the latest MetSim version but the ms.state appears to give the state at the start of the simulation. Is there an alternative way to obtain the state at the end of the simulation?

**Comment by kwhitney727** [comment]
[wrap_metsim_over_time.py](https://github.com/kwhitney727/MetSim/blob/feature/time_wrap/scripts/wrap_metsim_over_time.py)

**Comment by arbennett** [comment]
You should be able to get the necessary state data for a restart file manually by using: 
```
xr.concat([ms.state, ms.met_data], dim='time').isel(time=slice(-90, None)))
```

Also, you should be able to run MetSim over multiple forcing files all in one go by specifying a wildcard in the configuration entry for forcings. Something like the following:

```
MetSim:
    time_step: 30
    start: 1950-1-1
    stop: 1960-1-31
    forcing: 'test_*.nc'      # <----- note * here!
    domain: 'domain.nc'
    state: '.state.nc'
    out_dir: './results'
    out_prefix: 'yaml_output'

out_vars:
    temp:
        units: 'K'
    prec:
        units: 'mm s-1'
    shortwave:
        out_name: 'shortwave'
    air_pressure:
        units: 'kPa'

chunks:
    lat: 3
    lon: 3

forcing_vars:
    prec  : 'Prec'
    t_max : 'Tmax'
    t_min : 'Tmin'

state_vars:
    prec  : 'prec'
    t_max : 't_max'
    t_min : 't_min'

domain_vars:
    lat  : 'lat'
    lon  : 'lon'
    mask : 'mask'
    elev : 'elev'
```

**Comment by kwhitney727** [comment]
Both of these suggestions worked, thank you! 

I am not sure if it is documented anywhere that the MetSim can be run with multiple NetCDF forcing files using a wildcard specification. If not, it might be useful to add to the "Input Specifications" documentation page that the forcing "can either be the path to a NetCDF file, **or the path to a directory containing multiple NetCDF files**, or the ASCII or binary data (in the VIC4 format)", rather than simply "either be the path to a NetCDF file, or the path to a directory containing ASCII or binary data (in the VIC4 format). " Then also to add to the "Configuration Specifications" that multiple forcing files can be specified with the wildcard character.
