### ISSUE TITLE
 a one-day delay in the output compared to the input data

### ISSUE THREAD

**Issue by luoxiao11** [UW-Hydro/MetSim#261]
We found that there is a one-day(24-hour) shift between the input data and the MetSim output. The output data consistently shows a one-day delay compared to the input data. After conducting several tests, we have verified that it is because MetSim mandates longitudes to be confined within the range of [-180, 180], so it might not adequately process cases where the input data's longitude range spans [0-360].

**Comment by arbennett** [comment]
Fixed in #262
