### ISSUE TITLE
RuntimeWarning: overflow encountered

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#33]
I'm getting the following Error from the `mtclim` portion of the code:

```
mtclim.py:179: RuntimeWarning: overflow encountered in exp
  return tdew, svp(tdew)
```

**Comment by bartnijssen** [comment]
@arbennett : Have you noticed this as well? Would be good to get a bit more info on this (it comes from `numpy`)

**Comment by arbennett** [comment]
I have not.  @jhamman was this fixed in your refactor?

**Comment by jhamman** [comment]
I'm no longer able to reproduce this so whatever bug this was, it is no longer with us. I'll close for now and can reopen if I find it again.
