### ISSUE TITLE
Enable subdaily precipitation

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/MetSim#42]
Allow for subdaily precipitation that is not uniformly distributed throughout the day. 

This will be included as an option.

**Comment by jhamman** [comment]
@tbohn has an approach he think would work here.

**Comment by tbohn** [comment]
There are 2 parts: 1. enable reading of a netcdf file containing 2 parameters: peak time and duration, each of which has 12 monthly values per grid cell (so, dims = (time, lat, lon)); 2. function to disaggregate daily precip based on the parameters in part 1.

**Comment by arbennett** [comment]
A solution to the first part that would be relatively easy is to put those parameters into the domain file (where we currently store the elevation data).  If those parameters are put in the same dataset as the elevation then you would get them for free.  

Part 2 I would envision a setup like the way we select out the longwave calculation method, if the function is smaller.  If the method takes a significant amount of code to implement we might have to think a little bit deeper.

**Comment by tbohn** [comment]
OK, I'll assume the parameters will be in the domain file (or not at all).  Reading them will be optional (if precip disaggregation not selected, no attempt will be made to read them).

**Comment by arbennett** [comment]
This is implemented in #104
