### ISSUE TITLE
Advanced logging control

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#43]
The current MetSim code base prints to standard out using simple `print` statements. This doesn't leave the user with any control over how much gets printed. We should use the `logging` module and allow for users to specify the verbosity in the configuration file.

**Comment by arbennett** [comment]
This has the same topic as #18 so I'm going to close that one.

**Comment by bartnijssen** [comment]
@arbennett : Actually you should close the newer one and leave the old one open. You should have just marked this one as duplicate. Otherwise the discussion gets more and more fragmented.
