### ISSUE TITLE
API docs are not building correctly

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#50]
http://metsim.readthedocs.io/en/develop/api.html

**Comment by bartnijssen** [comment]
Is it not building correctly or simply incomplete? It's not clear what you mean with `not building correctly`.

**Comment by arbennett** [comment]
The API docs weren't building correctly because we did not have the correct conda environment set up on readthedocs.  There is a current issue with the conda build in the readthedocs container, so this issue is still not resolved.

**Comment by arbennett** [comment]
Solved in #59
