### ISSUE TITLE
DOC: Write FAQs

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#51]
To start, we should answer these questions:

1. Why did we develop MetSim?
1. How is MetSim related to VIC and MTCLIM)
1. What other Meteorological forcing disaggregation tools should I know about?
1. How should I cite metsim?

currently, the FAQ page on readthedocs is blank.

**Comment by bartnijssen** [comment]
This info should be available for the 0.1.0 release as well

**Comment by arbennett** [comment]
I think MetSim is a simple enough tool that we don't need this page, it can be easily covered in the overview.
