### ISSUE TITLE
DOC: MetSim Overview page

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#53]
We need to write an overview page for what metsim, it should include the following sections:

1. What is metsim?
2. What methods are included in metsim?
3. What are our goals and aspirations for the metsim package?

**Comment by bartnijssen** [comment]
Seems to have a lot of overlap with the FAQ. No need to duplicate info. The overview info should include citation info as well.

**Comment by arbennett** [comment]
This was fixed in #45
