### ISSUE TITLE
TESTING: benchmarking metsim

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#55]
I think @arbennett has already done some initial benchmarking (cProfile?) and optimization (numba) on the `mtclim` method in metsim. I think it would be really useful to build a baseline benchmarking setup on a real dataset so we can test how changes in the driver impact runtime. I'm open to ideas on how to do this.

**Comment by bartnijssen** [comment]
Sounds good but I am going to take @arbennett off of this. This is an open-ended effort and there are more pressing concerns. Also not a requirement for release of V1.0.0 (but fine it if is completed by then).

**Comment by arbennett** [comment]
Just to leave a comment on this, I have some stats from my scaling runs for 1 year @ hourly output: 
 -~1.2 GB / 1000 grid cells on main process, ~ 1 GB / worker process
 - On an interactive node on Hyak we can scale with ~100% cpu usage at `-n 8` 
 For 6000 grid cells:

Process count | Runtime
-------------------|-----------------
2                      | 11m 58s
4                      | 6m 27s
6                      | 4m 39s
8                      | 3m 47s
10                    | 3m 7s
12                    | 2m 52s

**Comment by arbennett** [comment]
I'd like to add, I think the base memory usage on the main process might be a bit high in my initial example.  For a ~24k grid cells the main process uses ~22GB.  I think the difference is because my smaller dataset has the same bounding box as the larger one, but only values in a single basin.

**Comment by bartnijssen** [comment]
What happens when you crop the bounding box?

**Comment by arbennett** [comment]
I think we can close this per the scaling study that is in the paper submitted to GMD.
