### ISSUE TITLE
User defined reader/writer functions for unconventional data stores

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#67]
The flexibility of MetSim is going to encourage users to attempt to use the tool on a variety of different datasets. We should allow users, through the Python API, to define new reader/writer methods for their dataset. Rather than creating/maintaining these for all possible datasets (VIC4, VIC5, SUMMA, SAC, etc.), we should just expose an API that allows users to do this themselves.

**Comment by arbennett** [comment]
Though not fully fixed in #75, it provided a relatively good solution by allowing users to script MetSim and input the required data as in memory xarray datasets.
