### ISSUE TITLE
Use of pd.date_range breaks compatibility with non-standard calendars

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#71]
I'm starting to use MetSim to disaggregate some met data that uses the `noleap` calendar. Currently, we are using `pd.date_range` in a bunch of places in `metsim.py` and we should probably move toward a more naive calendar approach.

I think I see a fairly clear way to do this but wanted to check with @bartnijssen and @arbennett before I jump in.

**Comment by bartnijssen** [comment]
Maybe explain first how you would do this. I don't really want to give up on using pandas time series capabilities unless there is a significant upside. Can `noleap` be treated as a special case? So just give some info on you implementation plan.

**Comment by jhamman** [comment]
Certainly. We'll still use pandas, just not `pd.date_range` directly. I'm thinking we can replace almost all the current uses of pd.date_range` with the time coordinate from xarray (works with pandas) or a custom function that looks something like this:

```Python
def date_range(calendar='standard', **kwargs):
    if calendar == 'standard':
        return pd.date_range(**kwargs)
    else:
        # special case
        return custom_date_range_for_noleap(**kwargs) . # I'll write this using xarray/netcdftime
```

**Comment by bartnijssen** [comment]
Yes - I think that should be fine (in either implementation). As long as we still operate on pandas or xarray timeseries that should work just fine
