### ISSUE TITLE
Domain and Forcing NetCDF dimensions need to match?

### ISSUE THREAD

**Issue by kandread** [UW-Hydro/MetSim#72]
Do the lat/lon dimensions in the domain file and the daily forcing NetCDF file need to be identical? I was trying to generate forcings for a subset of CONUS using Ben's NetCDF files as inputs, but was getting an error since the locations that were picked up from the domain file (in terms of i,j) were not matching what was in the daily forcing file (e.g. location (1,1) in the domain file ended up pulling NaNs from the daily forcing file, making the disaggregation crash). I put in a simple fix in my fork, but wanted to check first in case there's something else that was causing me problems. Thanks!

**Comment by arbennett** [comment]
Yes, as we have the code now, the mismatch would be your problem.  I checked out your fix, and think it's a good way to go.  If you open a pull request we can merge this into the main repo and fix the issue.

**Comment by kandread** [comment]
Sounds good. I'll create the pull request asap.
