### ISSUE TITLE
Should we take into account distance from center of time zone?

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#8]
In the original code the distance from the center of the time zone is calculated by 

`hour_offset = (theta_l - theta_s) * 24 / 360`

and is used in the disaggregation of shortwave radiation:

`tiny_step = j*tinystepperhour + k - tiny_offset`

Where `tiny_offset` is just a scaling of `hour_offset`.

The `theta_l` and `theta_s` parameters come from a struct returned by `read_soilparam.c`, which doesn't have any implementation in MetSim right now.

**Comment by arbennett** [comment]
@bartnijssen @jhamman Do either of you have thoughts on whether/how we should implement this?  Perhaps these parameters can be set in the configuration file?

**Comment by jhamman** [comment]
Yes, I do think we should maintain this feature.

**Comment by arbennett** [comment]
Would it be reasonable to pull the lats and lons from the forcing file name?  Or rather, is it to onerous to enforce the forcing naming standard `$NAME_$LAT_$LON`?  If we enforce this, the theta parameters could be calculated from these directly.

**Comment by jhamman** [comment]
I don't really like using the filename as metadata. For the traidtional VIC input, this may be okay but the most common application of this tool will probably be netcdf->netcdf.

**Comment by bartnijssen** [comment]
We should not pull this from the forcing file name. That's an old VIC habit in classic mode,  but we should not assume that going forward. For example, it won't be available when we write in netCDF mode

**Comment by arbennett** [comment]
Solved in #10.
