### ISSUE TITLE
Add conda recipe and distribute via UW-Hydro channel

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#80]
The current MetSim docs for installation basically instructs users to install the MetSim dependencies via `conda`, then install MetSim via `pip`. We should just put MetSim in our conda channel so we can use conda for everything. 

RVIC will provide a good demonstration of how this can work: https://github.com/UW-Hydro/conda-recipes-uwhydro/issues/1

**Comment by arbennett** [comment]
This has been solved for OSX and Linux, do we want to support Windows on this end?  The pip version is platform agnostic, and MetSim isn't really targeted at Windows machines, so I'm okay with not maintaining it. Thoughts @jhamman @bartnijssen ?

**Comment by jhamman** [comment]
@arbennett - So you built MetSim using this approach:

```
conda skeleton pypi MetSim
conda build MetSim
anaconda upload /Users/jhamman/anaconda/conda-bld/osx-64/metsim-1.0-py35_0.tar.bz2 -u UW-Hydro

```

**Comment by arbennett** [comment]
Yep.

**Comment by bartnijssen** [comment]
@arbennett : Does anything else need to happen here?

I am fine with not maintaining a windows install since we have no good place to test them, as long as we make that clear somewhere in the docs.

**Comment by jhamman** [comment]
I am in the process of putting metsim into conda-forge: https://github.com/conda-forge/staged-recipes/pull/5130

I think once that is done, plus an update to the docs, we can close this for good.

**Comment by jhamman** [comment]
closed via https://github.com/conda-forge/staged-recipes/pull/5130
