### ISSUE TITLE
Additional time handling functionality

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/MetSim#92]
The most common error I've run into when running MetSim is related to ill-specified time values of one kind or another. This could be in the state file, configuration file, or in the forcing file. All this leads me to think we could use 

1) some more robust validation of the time variables in MetSim,
2) some more instructive errors when things go wrong, and
3) a new feature to infer run length from the forcing file.

The underlying goal is to make the running/output of MetSim predictable with regards to the specification of input/output times.

cc @arbennett: following up on our personal conversation yesterday

**Comment by arbennett** [comment]
Solved in #93
