### ISSUE TITLE
Add wind to the sample datasets

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/MetSim#99]
This is so that the end result of MetSim will be consistent with an input into VIC.  Otherwise, a new VIC user might assume that one should just run MetSim as shown in the sample dataset, and then get an error when attempting to run VIC with those outputs.

For pressure, the fix is very simple; just specify pressure as an output variable in the sample config file.
For wind, someone will have to put reasonable daily wind values into the input daily meteorology file.   Here at ASU we might be able to do that.

The VIC error when wind is not present is also not very informative (it says there's an error reading a variable from the forcing file, but because the config file was set up to cover only those variables that were actually in the forcing file, which lacked wind, the VIC error message didn't actually know the name of the wind variable).  I realize this is a VIC issue rather than a MetSim issue.  But still, this is the type of situation that will arise.

**Comment by tbohn** [comment]
Thanks Andrew, and please pardon my ignorance of the details.  I'm not the one working on MetSim directly, so while I see parts of the code during our code discussions/reviews, I don't see the whole system.

**Comment by arbennett** [comment]
No worries, I just try to keep these issues documented so it's easy for others to follow.

**Comment by arbennett** [comment]
Done in #155
